In [3]:
import torch
import numpy as np

In [4]:
# Addition
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
# Division
(tensor_b / tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [19]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponent/Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# Reassignment