In [1]:
import torch

In [2]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
## Reshape and view
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Reshape if we dont know the no.of items -> using -1
my_tensor2 = torch.arange(15)
my_tensor2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
my_tensor2 = my_tensor2.reshape(3,-1)
my_tensor2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
# Slices
my_tensor3 = torch.arange(15)
my_tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
my_tensor4 = my_tensor3.reshape(5,3)
my_tensor4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [17]:
my_tensor4[:,2]

tensor([ 2,  5,  8, 11, 14])

In [18]:
my_tensor4[:,2:]

tensor([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])