In [1]:
import torch

In [2]:
import numpy as np

In [3]:
list1 = [1,34,452,34,5]
list1

[1, 34, 452, 34, 5]

In [5]:
np1 = np.random.rand(2,3)
np1

array([[0.10368093, 0.49187498, 0.37785764],
       [0.01596108, 0.37702172, 0.61535377]])

In [8]:
tensor_2d = torch.rand(2,3)
tensor_2d

tensor([[0.4872, 0.1637, 0.0385],
        [0.1316, 0.5834, 0.6484]])

In [9]:
tensor_3d = torch.zeros(2,3,4) 
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1037, 0.4919, 0.3779],
        [0.0160, 0.3770, 0.6154]], dtype=torch.float64)